name: Mirror Repository

on:
  push:
    branches: [ main, master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Mirror to Swarm-by-CHI/swarm-ai-trading-agent
        run: |
          git remote add target https://x-access-token:${{ secrets.REPO_MIRROR_TOKEN }}@github.com/Swarm-by-CHI/swarm-ai-trading-agent.git
          git push target --all --force
          git push target --tags --force 